services:
  - type: web
    runtime: node
    name: seven-joetheproz5
    rootDir: Web
    buildCommand: ""
    startCommand: node server.js
    healthCheckPath: /
    plan: free
    envVars:
      - key: TMDB_BEARER_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_PUBLISHABLE_KEY
        sync: false
      - key: SUPABASE_EMAIL_REDIRECT_TO
        sync: false
