#!/usr/bin/env python3
"""Generate iOS PWA launch PNGs and the matching startup-theme.css.

Requires Pillow: python -m pip install Pillow
The source of truth is ../startup-theme.json; device dimensions and DPR are
read from apple-touch-startup-image media queries in ../index.html.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw


WEB = Path(__file__).resolve().parents[1]
CONFIG_PATH = WEB / "startup-theme.json"
INDEX_PATH = WEB / "index.html"
THEME_CSS_PATH = WEB / "startup-theme.css"


def parse_color(value: str) -> tuple[int, int, int]:
    value = value.lstrip("#")
    if len(value) != 6:
        raise ValueError(f"Expected #RRGGBB color, got {value!r}")
    return tuple(int(value[i : i + 2], 16) for i in (0, 2, 4))


def css_color(value: str) -> str:
    return value.lower()


def css_rgba(color: str, alpha: float) -> str:
    red, green, blue = parse_color(color)
    return f"rgba({red}, {green}, {blue}, {alpha:g})"


def read_specs(index_html: str) -> list[dict[str, int | str]]:
    tags = re.findall(r"<link\b[^>]*>", index_html, flags=re.IGNORECASE)
    specs: list[dict[str, int | str]] = []
    for tag in tags:
        rel = re.search(r'\brel="([^"]+)"', tag, re.IGNORECASE)
        if not rel or rel.group(1).lower() != "apple-touch-startup-image":
            continue
        media = re.search(r'\bmedia="([^"]+)"', tag, re.IGNORECASE)
        href = re.search(r'\bhref="([^"]+)"', tag, re.IGNORECASE)
        if not media or not href:
            raise ValueError(f"Incomplete startup-image link: {tag}")
        media_text = media.group(1)
        width = re.search(r"device-width\s*:\s*(\d+)px", media_text)
        height = re.search(r"device-height\s*:\s*(\d+)px", media_text)
        dpr = re.search(r"-webkit-device-pixel-ratio\s*:\s*(\d+)", media_text)
        orientation = re.search(r"orientation\s*:\s*(portrait|landscape)", media_text)
        if not all((width, height, dpr, orientation)):
            raise ValueError(f"Unsupported startup-image media query: {media_text}")
        output = href.group(1).split("?", 1)[0]
        name = Path(output).name
        dimensions = re.fullmatch(r"(\d+)x(\d+)\.png", name)
        if not dimensions:
            raise ValueError(f"Unexpected startup-image filename: {name}")
        pixel_width, pixel_height = map(int, dimensions.groups())
        css_width, css_height, scale = int(width.group(1)), int(height.group(1)), int(dpr.group(1))
        if (pixel_width, pixel_height) != (css_width * scale, css_height * scale):
            raise ValueError(f"{name} does not match its {css_width}x{css_height} @ {scale}x media query")
        specs.append({
            "output": output,
            "name": name,
            "pixel_width": pixel_width,
            "pixel_height": pixel_height,
            "css_width": css_width,
            "css_height": css_height,
            "dpr": scale,
            "orientation": orientation.group(1).lower(),
            "media": media_text,
        })
    if not specs:
        raise ValueError("No apple-touch-startup-image entries found in index.html")
    if len({spec["output"] for spec in specs}) != len(specs):
        raise ValueError("Duplicate startup-image output paths in index.html")
    return specs


def generated_css(config: dict, specs: list[dict[str, int | str]]) -> str:
    background = config["background"]
    logo = config["logo"]
    glow_x, glow_y = background["glowCenter"]
    glow_rx, glow_ry = background["glowRadii"]
    logo_width, logo_height = logo["aspectRatio"]
    midpoint = background["middleStop"] * 100
    glow = (
        f"radial-gradient(ellipse {glow_rx * 100:g}% {glow_ry * 100:g}% at "
        f"{glow_x * 100:g}% {glow_y * 100:g}%, "
        f"{css_rgba(background['glowColor'], background['glowOpacity'])} 0%, transparent {background['glowFadeStop'] * 100:g}%), "
        f"linear-gradient(180deg, {css_color(background['topColor'])} 0%, "
        f"{css_color(background['middleColor'])} {midpoint:g}%, "
        f"{css_color(background['bottomColor'])} 100%)"
    )
    css = (
        "/* Generated by scripts/generate_ios_splash.py from startup-theme.json. */\n"
        ":root {\n"
        f"  --seven-startup-background-color: {css_color(background['baseColor'])};\n"
        f"  --seven-startup-background: {glow};\n"
        f"  --seven-startup-logo-width: min({logo['widthVw']}vw, {logo['maxWidthCssPx']}px);\n"
        f"  --seven-startup-logo-aspect-ratio: {logo_width} / {logo_height};\n"
        "}\n"
    )
    # On supported Apple devices, reuse the exact same full-screen PNG used by
    # the native launch image. This removes fractional CSS image scaling and
    # guarantees matching logo pixels during handoff.
    #
    # The image is anchored to the TOP of the viewport and sized by width only
    # (each PNG's aspect ratio equals its device screen's aspect ratio, enforced
    # by read_specs), never stretched to the container height. If the web view's
    # first painted frames get a transiently short layout viewport, a
    # height-stretched logo would ride up with it — the "ghost" double above the
    # sharp mark during the native→web crossfade. With top anchoring, the
    # wordmark's position derives from screen width (which does not glitch), so
    # it lands exactly where the native launch image drew it regardless of the
    # transient container height. The uniform dark background makes the clipped
    # overflow invisible.
    for spec in specs:
        css += (
            f"@media {spec['media']} {{\n"
            "  .seven-intro .startup-intro-mark {\n"
            "    position: absolute; top: 0; left: 0; width: 100%; height: auto;\n"
            "    max-width: none; aspect-ratio: auto; object-fit: fill;\n"
            "  }\n"
            "}\n"
        )
    return css


def interpolate(a: tuple[int, int, int], b: tuple[int, int, int], t: float) -> tuple[int, int, int]:
    return tuple(round(start + (end - start) * t) for start, end in zip(a, b))


def make_background(width: int, height: int, config: dict) -> Image.Image:
    settings = config["background"]
    top, middle, bottom = map(parse_color, (settings["topColor"], settings["middleColor"], settings["bottomColor"]))
    middle_stop = float(settings["middleStop"])
    vertical = Image.new("RGB", (1, height))
    draw = ImageDraw.Draw(vertical)
    for y in range(height):
        position = y / max(1, height - 1)
        color = interpolate(top, middle, position / middle_stop) if position <= middle_stop else interpolate(middle, bottom, (position - middle_stop) / (1 - middle_stop))
        draw.point((0, y), fill=color)
    canvas = vertical.resize((width, height), Image.Resampling.BICUBIC).convert("RGBA")

    # Pillow's radial gradient is a normalized black-center/white-edge mask.
    # Map it to the same single red radial layer used by the in-app CSS.
    center_x, center_y = settings["glowCenter"]
    radius_x, radius_y = settings["glowRadii"]
    glow = Image.radial_gradient("L")
    red, green, blue = parse_color(settings["glowColor"])
    opacity = float(settings["glowOpacity"])
    fade_stop = float(settings["glowFadeStop"])
    lut = []
    for value in range(256):
        distance = value / 255
        alpha = opacity * max(0.0, 1.0 - distance / fade_stop)
        lut.append(round(alpha * 255))
    glow = glow.point(lut).resize(
        (max(1, round(width * radius_x * 2)), max(1, round(height * radius_y * 2))),
        Image.Resampling.LANCZOS,
    )
    mask = Image.new("L", (width, height), 0)
    origin = (round(width * center_x - glow.width / 2), round(height * center_y - glow.height / 2))
    mask.paste(glow, origin)
    glow_layer = Image.new("RGBA", (width, height), (red, green, blue, 0))
    glow_layer.putalpha(mask)
    return Image.alpha_composite(canvas, glow_layer)


def make_splash(spec: dict, config: dict, logo: Image.Image) -> Image.Image:
    width, height = int(spec["pixel_width"]), int(spec["pixel_height"])
    dpr, css_width = int(spec["dpr"]), int(spec["css_width"])
    settings = config["logo"]
    display_width = round(min(css_width * settings["widthVw"] / 100, settings["maxWidthCssPx"]) * dpr)
    display_height = round(display_width * logo.height / logo.width)
    resized_logo = logo.resize((display_width, display_height), Image.Resampling.LANCZOS)
    canvas = make_background(width, height, config)
    center_x, center_y = settings["center"]
    position = (round(width * center_x - display_width / 2), round(height * center_y - display_height / 2))
    canvas.alpha_composite(resized_logo, dest=position)
    return canvas.convert("RGB")


def images_equal(left: Image.Image, right: Image.Image) -> bool:
    return left.size == right.size and ImageChops.difference(left.convert("RGB"), right.convert("RGB")).getbbox() is None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify generated assets without writing files")
    args = parser.parse_args()
    config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    index_html = INDEX_PATH.read_text(encoding="utf-8")
    specs = read_specs(index_html)
    logo_path = WEB / config["logo"]["source"]
    with Image.open(logo_path) as source:
        logo = source.convert("RGBA")
    expected_ratio = config["logo"]["aspectRatio"]
    if (logo.width, logo.height) != tuple(expected_ratio):
        raise ValueError(f"Logo dimensions changed: expected {expected_ratio[0]}x{expected_ratio[1]}, got {logo.width}x{logo.height}")
    css = generated_css(config, specs)
    failures = []
    if args.check:
        if not THEME_CSS_PATH.exists() or THEME_CSS_PATH.read_text(encoding="utf-8") != css:
            failures.append("startup-theme.css is stale; rerun the generator")
    else:
        THEME_CSS_PATH.write_text(css, encoding="utf-8", newline="\n")
    for spec in specs:
        output = WEB / str(spec["output"])
        expected = make_splash(spec, config, logo)
        if args.check:
            if not output.exists():
                failures.append(f"missing {spec['name']}")
                continue
            with Image.open(output) as current:
                if not images_equal(expected, current):
                    failures.append(f"{spec['name']} is stale or has the wrong dimensions")
        else:
            output.parent.mkdir(parents=True, exist_ok=True)
            expected.save(output, format="PNG", optimize=True)
    if failures:
        print("\n".join(failures), file=sys.stderr)
        return 1
    if args.check:
        print(f"OK: {len(specs)} launch PNGs and startup-theme.css match the shared theme.")
    else:
        print(f"Generated {len(specs)} launch PNGs and startup-theme.css.")
        for spec in specs:
            print(f"  {spec['name']}: {spec['css_width']}x{spec['css_height']} CSS px @ {spec['dpr']}x ({spec['orientation']})")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (KeyError, OSError, ValueError, json.JSONDecodeError) as error:
        print(f"startup asset generation failed: {error}", file=sys.stderr)
        raise SystemExit(1)
