const TMDB_IMAGE = "https://image.tmdb.org/t/p/w500";
const FEATURED_ID = 71712;
const app = document.querySelector("#app");
const state = { featured: null, featuredPool: [], featuredIndex: 0, heroTimer: null, heroAnimating: false, catalog: {}, route: "home", search: "", user: null, session: null, movie: null, trailer: null, progressTimer: null, pendingProgress: null };
const SESSION_KEY = "cineva.supabase.session";
const watchKey = item => `cineva-progress-${item.type}-${item.id}-${item.season || 0}-${item.episode || 0}`;
const titleOf = item => item.title || item.name || item.original_title || item.original_name || "Untitled";
const yearOf = item => (item.release_date || item.first_air_date || "").slice(0, 4);
const posterOf = item => item.poster_path ? `${TMDB_IMAGE}${item.poster_path}` : "/icon.svg";
const escapeHTML = value => String(value || "").replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
function scrollToTop() { window.scrollTo(0, 0); document.documentElement.scrollTop = 0; document.body.scrollTop = 0; }

async function localAPI(path, options = {}) { const response = await fetch(path, options); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || data.msg || "Request failed."); return data; }
function authorizedHeaders() { return state.session?.access_token ? { Authorization:`Bearer ${state.session.access_token}` } : {}; }
async function restoreSession() { try { state.session = JSON.parse(localStorage.getItem(SESSION_KEY) || "null"); if (!state.session?.access_token) return; state.user = await localAPI("/api/auth/user", { headers:authorizedHeaders() }); await loadCloudProgress(); } catch { localStorage.removeItem(SESSION_KEY); state.session = null; state.user = null; } }
async function loadCloudProgress() { const rows = await localAPI("/api/account/progress", { headers:authorizedHeaders() }); rows.forEach(row => localStorage.setItem(row.content_key, JSON.stringify({ currentTime:Number(row.progress_seconds), duration:Number(row.duration_seconds), progress:row.duration_seconds ? Number(row.progress_seconds) / Number(row.duration_seconds) * 100 : 0, watched:row.is_watched, type:row.content_type, id:row.tmdb_id, season:row.season, episode:row.episode, title:row.title, posterPath:row.poster_path, lastWatchedAt:row.last_watched_at }))); }

async function api(path, params = {}) {
  const query = new URLSearchParams(params); const response = await fetch(`/api/tmdb/${path}${query.size ? `?${query}` : ""}`);
  if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || "TMDB is not configured");
  return response.json();
}
async function boot() {
  renderLoading();
  await restoreSession();
  try {
    const [featured, trending, movies, shows, recent, airing] = await Promise.all([
      api(`tv/${FEATURED_ID}`), api("trending/all/week"), api("movie/popular"), api("tv/popular"), api("movie/now_playing"), api("tv/on_the_air")
    ]);
    state.featuredPool = shuffle([...results(recent), ...results(airing), ...results(trending)]).filter(item => item.backdrop_path).slice(0, 12);
    state.featured = state.featuredPool[0] || normalize(featured, "tv");
    state.catalog = { "Trending now": results(trending), "New movies": results(recent), "New series": results(airing), "Popular movies": results(movies), "Popular series": results(shows) };
  } catch (error) {
    state.featured = { id: FEATURED_ID, type: "tv", name: "The Good Doctor", overview: "Add a TMDB Read Access Token to enable posters, descriptions, categories, and search.", backdrop_path: null };
    state.catalog = {};
    state.error = error.message;
  }
  render();
}
function shuffle(items) { const copy = [...items]; for (let index = copy.length - 1; index > 0; index -= 1) { const target = Math.floor(Math.random() * (index + 1)); [copy[index], copy[target]] = [copy[target], copy[index]]; } return copy; }
function results(payload) { return (payload.results || []).filter(item => item.media_type !== "person").map(item => normalize(item)); }
function normalize(item, fallbackType) { return { ...item, type: item.type || (item.media_type === "movie" || item.title ? "movie" : fallbackType || "tv") }; }
function header() { const account = state.user ? `<button class="account signed-in" data-account title="Account">${escapeHTML((state.user.email || "U").slice(0, 1).toUpperCase())}</button>` : `<button class="account" data-auth aria-label="Open account"><span>◉</span><b>Account</b></button>`; return `<header><button class="wordmark logo-only" data-home aria-label="SEVEN home"><img src="/assets/seven-logo-red.png" alt="SEVEN"></button><nav aria-label="Main navigation"><button class="nav-link" data-home><svg class="nav-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1Z"/></svg><span>Home</span></button><button class="nav-link" data-for-you><svg class="nav-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 1.8 5.2L19 10l-5.2 1.8L12 17l-1.8-5.2L5 10l5.2-1.8ZM19 15l.8 2.2L22 18l-2.2.8L19 21l-.8-2.2L16 18l2.2-.8Z"/></svg><span>For You</span></button><button class="nav-link" data-movies><svg class="nav-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h16v15H4Z M4 9h16 M8 5l3 4m2-4 3 4M8 20l3-4m2 4 3-4"/></svg><span>Movies</span></button><button class="nav-link" data-shows><svg class="nav-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M8 2 5 5m11-3 3 3m-7 4 4 3-4 3Z"/></svg><span>Series</span></button></nav><label class="search"><span>⌕</span><input id="search" value="${escapeHTML(state.search)}" placeholder="Titles, movies, series" autocomplete="off"></label>${account}</header>`; }
function footer() { return `<footer class="site-footer"><div class="footer-wordmark" aria-hidden="true">SEVEN</div><div class="footer-inner"><span class="brand">WHAT WILL YOU WATCH?</span><p>SEVEN brings movies and series into one calm place—so choosing your next watch feels effortless.</p><nav class="footer-links" aria-label="Footer navigation"><button data-home>Start here</button><button data-for-you>Picked for you</button><button data-movies>Film library</button><button data-shows>Series library</button><button data-search-focus>Find a title</button></nav><small>Title details, artwork, and trailers are powered by <a href="https://www.themoviedb.org/" target="_blank" rel="noreferrer">TMDB</a>. SEVEN uses the TMDB API but is not endorsed or certified by TMDB. TMDB provides metadata only, not playback rights.</small></div></footer>`; }
function render() { if (state.route === "player") return renderPlayer(); if (state.route === "movie") return renderMovie(); if (state.route === "series") return renderSeries(); if (state.route === "search") return renderSearch(); if (state.route === "for-you") return renderForYou(); if (state.route === "catalog") return renderCatalog(); if (state.route === "all-catalog") return renderAllCatalog(); if (state.route === "explore") return renderExplore(); renderHome(); }
function renderLoading() { app.innerHTML = `<header><span class="wordmark logo-only"><img src="/assets/seven-logo-red.png" alt="SEVEN"></span></header><section class="hero skeleton"></section><section class="rail"><div class="skeleton-line wide"></div><div class="cards">${Array.from({length:7}, () => `<div class="card-skeleton skeleton"></div>`).join("")}</div></section><section class="rail"><div class="skeleton-line"></div><div class="cards">${Array.from({length:7}, () => `<div class="card-skeleton skeleton"></div>`).join("")}</div></section>`; }
function renderHome() {
  clearInterval(state.heroTimer);
  const f = state.featured;
  const continuing = continueWatching();
  app.innerHTML = `${header()}<section class="hero" id="featured">${featuredMarkup(f)}</section>${state.error ? `<p class="setup">TMDB setup needed: ${escapeHTML(state.error)}. See README.</p>` : ""}${continuing.length ? continueRail(continuing) : ""}<div id="rails">${Object.entries(state.catalog).map(([name, items]) => rail(name, items)).join("")}</div>${footer()}`;
  bindCommon(); bindFeatured(); scheduleHero();
}
function heroDots() { const count = Math.min(5, state.featuredPool.length), active = Math.round(state.featuredIndex / Math.max(1, state.featuredPool.length - 1) * Math.max(0, count - 1)); return Array.from({ length:count }, (_, index) => `<i class="${index === active ? "active" : ""}"></i>`).join(""); }
function heroCover(offset) { const length = state.featuredPool.length; if (!length) return ""; const item = state.featuredPool[(state.featuredIndex + offset + length) % length], side = offset < 0 ? "prev" : offset > 0 ? "next" : "center", depth = Math.min(Math.abs(offset), 2), action = offset ? `data-hero-${side}` : `data-open="${item.type}:${item.id}"`; return `<button class="hero-cover hero-cover-${side}-${depth}" ${action} aria-label="${offset ? `Show ${escapeHTML(titleOf(item))}` : `Open ${escapeHTML(titleOf(item))}`}"><img src="${posterOf(item)}" alt="" loading="eager"><span>${escapeHTML(titleOf(item))}</span></button>`; }
function heroCoverflow() { return state.featuredPool.length > 1 ? `<div class="hero-coverflow" aria-label="Featured titles">${[-2, -1, 0, 1, 2].map(heroCover).join("")}</div>` : ""; }
function featuredMarkup(item) { const navigation = state.featuredPool.length > 1 ? `<div class="hero-nav"><button class="hero-arrow" data-hero-prev aria-label="Previous featured title">‹</button><span class="hero-index">${String(state.featuredIndex + 1).padStart(2, "0")} <i></i> ${String(state.featuredPool.length).padStart(2, "0")}</span><button class="hero-arrow" data-hero-next aria-label="Next featured title">›</button></div>` : ""; return `<span class="hero-kicker">SEVEN SPOTLIGHT</span>${heroCoverflow()}${navigation}`; }
function bindCoverflowGestures() { const flow = document.querySelector("#featured .hero-coverflow:not(.hero-coverflow-outgoing)"); if (!flow) return; let startX = 0, dragging = false, swallowClick = false, lastWheel = 0; flow.addEventListener("pointerdown", event => { startX = event.clientX; dragging = false; }); flow.addEventListener("pointermove", event => { if (startX && Math.abs(event.clientX - startX) > 8) dragging = true; }); flow.addEventListener("pointerup", event => { const distance = event.clientX - startX; startX = 0; if (!dragging || Math.abs(distance) < 42) return; swallowClick = true; rotateHero(distance < 0 ? 1 : -1); setTimeout(() => { swallowClick = false; }, 0); }); flow.addEventListener("pointercancel", () => { startX = 0; dragging = false; }); flow.addEventListener("click", event => { if (!swallowClick) return; event.preventDefault(); event.stopImmediatePropagation(); }, true); flow.addEventListener("wheel", event => { if (Math.abs(event.deltaX) < 18 || Date.now() - lastWheel < 500) return; event.preventDefault(); lastWheel = Date.now(); rotateHero(event.deltaX > 0 ? 1 : -1); }, { passive:false }); }
function bindFeatured() { document.querySelectorAll("#featured [data-open]").forEach(button => button.onclick = () => { const [type, id] = button.dataset.open.split(":"); openItem(type, id); }); document.querySelectorAll("#featured [data-hero-prev]").forEach(button => button.addEventListener("click", () => rotateHero(-1))); document.querySelectorAll("#featured [data-hero-next]").forEach(button => button.addEventListener("click", () => rotateHero(1))); bindCoverflowGestures(); }
function rotateHero(direction = 1) { if (state.featuredPool.length < 2 || state.heroAnimating) return; const hero = document.querySelector("#featured"), flow = hero?.querySelector(".hero-coverflow:not(.hero-coverflow-outgoing)"); if (!hero || !flow) return; state.heroAnimating = true; flow.classList.add(direction > 0 ? "hero-moving-next" : "hero-moving-prev"); setTimeout(() => { state.featuredIndex = (state.featuredIndex + direction + state.featuredPool.length) % state.featuredPool.length; state.featured = state.featuredPool[state.featuredIndex]; hero.innerHTML = featuredMarkup(state.featured); bindFeatured(); state.heroAnimating = false; }, 460); }
function scheduleHero() { if (state.featuredPool.length > 1) state.heroTimer = setInterval(() => { if (state.route === "home") rotateHero(); }, 8500); }
function railIcon(name) { const key = name.toLowerCase(), icon = key.includes("continue") ? `<path d="M3 12a9 9 0 1 0 3-6.7M3 4v5h5M12 7v5l3 2"/>` : key.includes("trend") ? `<path d="m3 17 6-6 4 4 7-8M15 7h5v5"/>` : key.includes("series") ? `<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m8 2-3 3m11-3 3 3m-7 4 4 3-4 3Z"/>` : key.includes("movie") ? `<path d="M4 5h16v15H4ZM4 9h16M8 5l3 4m2-4 3 4M8 20l3-4m2 4 3-4"/>` : `<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z"/>`; return `<span class="rail-icon" aria-hidden="true"><svg viewBox="0 0 24 24">${icon}</svg></span>`; }
function railTitle(name) { return `<h2 class="rail-heading">${railIcon(name)}<span>${escapeHTML(name)}</span></h2>`; }
function rail(name, items) { const key = `${state.route}:${name}`; state.explorable ||= {}; state.explorable[key] = { name, items, fromRoute:state.route }; return `<section class="rail"><div class="rail-title">${railTitle(name)}<button class="explore-all" data-explore="${escapeHTML(key)}">Explore all</button></div><div class="cards">${items.map(card).join("")}</div></section>`; }
function card(item) { return `<button class="card" data-open="${item.type}:${item.id}"><span class="poster-wrap"><img src="${posterOf(item)}" alt="" loading="lazy"><i>${item.type === "tv" ? "SERIES" : "MOVIE"}</i><strong class="card-play" aria-hidden="true">▶</strong></span><b>${escapeHTML(titleOf(item))}</b><small>${yearOf(item) || "New"}${item.vote_average ? ` · ★ ${item.vote_average.toFixed(1)}` : ""}</small></button>`; }
function continueWatching() { const seen = new Set(); return Object.keys(localStorage).filter(key => key.startsWith("cineva-progress-")).map(key => { try { return JSON.parse(localStorage.getItem(key) || "{}"); } catch { return null; } }).filter(item => item?.type && item.id && item.title && Number(item.duration) > 0 && Number(item.duration) - Number(item.currentTime) >= 600 && !item.watched).sort((a, b) => new Date(b.lastWatchedAt || 0) - new Date(a.lastWatchedAt || 0)).filter(item => { const key = `${item.type}:${item.id}`; if (seen.has(key)) return false; seen.add(key); return true; }).slice(0, 16); }
function continueRail(items) { return `<section class="rail continue-rail"><div class="rail-title">${railTitle("Continue watching")}<span>Pick up where you left off</span></div><div class="cards">${items.map(item => `<button class="card continue-card" data-continue="${escapeHTML(`${item.type}:${item.id}:${item.season || 0}:${item.episode || 0}`)}"><span class="poster-wrap"><img src="${item.posterPath ? TMDB_IMAGE + item.posterPath : "/icon.svg"}" alt="" loading="lazy"><i>${item.type === "tv" ? `S${item.season} · E${item.episode}` : "MOVIE"}</i><strong class="card-play" aria-hidden="true">▶</strong></span><b>${escapeHTML(item.title)}</b><small>Resume from ${timeLabel(Math.floor(item.currentTime || 0))}</small><em class="continue-progress"><i style="width:${Math.min(100, Number(item.progress) || 0)}%"></i></em></button>`).join("")}</div></section>`; }
async function openItem(type, id) {
  scrollToTop();
  try {
    const item = normalize(await api(`${type}/${id}`, { append_to_response:"credits,keywords,videos" }), type);
    state.trailer = trailerFrom(item.videos) || await loadTrailer(type, item.id);
    if (type === "movie") { state.movie = item; state.route = "movie"; }
    else { state.series = item; state.selectedSeason = 1; state.route = "series"; await loadEpisodes(); }
  } catch (error) { state.error = error.message; state.route = "home"; }
  render(); scrollToTop();
}
async function loadEpisodes() { state.episodes = await api(`tv/${state.series.id}/season/${state.selectedSeason}`); }
function trailerFrom(videos) { return (videos?.results || []).find(video => video.site === "YouTube" && video.type === "Trailer") || (videos?.results || []).find(video => video.site === "YouTube") || null; }
async function loadTrailer(type, id) { try { return trailerFrom(await api(`${type}/${id}/videos`)); } catch { return null; } }
function trailerAction() { return state.trailer ? `<button class="secondary" data-trailer><b>▷</b> Trailer</button>` : ""; }
function mediaInfo(item, type) { const credits = item.credits || {}, cast = (credits.cast || []).slice(0, 18), keywords = (item.keywords?.keywords || item.keywords?.results || []).slice(0, 18), people = type === "movie" ? (credits.crew || []).filter(person => ["Director","Writer","Screenplay"].includes(person.job)).slice(0, 4) : (item.created_by || []).slice(0, 4); const facts = type === "movie" ? [["Type","Movie"],["Released",item.release_date || "—"],["Runtime",item.runtime ? `${item.runtime} min` : "—"],["Status",item.status || "—"],["Language",(item.original_language || "—").toUpperCase()],["Countries",(item.production_countries || []).map(country => country.iso_3166_1).join(", ") || "—"]] : [["Type","Series"],["First aired",item.first_air_date || "—"],["Last aired",item.last_air_date || "Ongoing"],["Seasons",item.number_of_seasons || "—"],["Episodes",item.number_of_episodes || "—"],["Status",item.status || "—"],["Language",(item.original_language || "—").toUpperCase()],["Networks",(item.networks || []).map(network => network.name).join(", ") || "—"]]; return `<section class="media-info"><div class="info-block"><span class="brand">ABOUT</span><div class="fact-grid">${facts.map(([label, value]) => `<div><small>${escapeHTML(label)}</small><b>${escapeHTML(value)}</b></div>`).join("")}</div></div><div class="info-block"><span class="brand">GENRES</span><div class="tag-row">${(item.genres || []).map(genre => `<span>${escapeHTML(genre.name)}</span>`).join("") || "<span>Not listed</span>"}</div></div>${people.length ? `<div class="info-block"><span class="brand">${type === "movie" ? "CREW" : "CREATED BY"}</span><p class="creator-list">${people.map(person => `${escapeHTML(person.name)}${person.job ? ` · ${escapeHTML(person.job)}` : ""}`).join("<br>")}</p></div>` : ""}${keywords.length ? `<div class="info-block"><span class="brand">KEYWORDS</span><div class="tag-row">${keywords.map(keyword => `<span>${escapeHTML(keyword.name)}</span>`).join("")}</div></div>` : ""}${cast.length ? `<div class="info-block cast-block"><span class="brand">CAST</span><div class="cast-row">${cast.map(person => `<article class="cast-card"><img src="${person.profile_path ? TMDB_IMAGE + person.profile_path : "/icon.svg"}" alt="${escapeHTML(person.name)}" loading="lazy"><b>${escapeHTML(person.name)}</b><small>${escapeHTML(person.character || "Cast")}</small></article>`).join("")}</div></div>` : ""}</section`; }
function renderMovie() {
  const movie = state.movie;
  app.innerHTML = `${header()}<button class="back" data-home>‹ Browse</button><section class="detail"><img src="${posterOf(movie)}" alt="${escapeHTML(titleOf(movie))}"><div><span class="brand">MOVIE</span><h1>${escapeHTML(titleOf(movie))}</h1><div class="meta"><span>${yearOf(movie)}</span><i></i><span>${movie.runtime ? `${movie.runtime} min` : "Movie"}</span><i></i><span>${movie.vote_average ? `★ ${movie.vote_average.toFixed(1)}` : "TV-14"}</span></div><p>${escapeHTML(movie.overview || "")}</p><div class="actions"><button class="primary" data-play-movie><b>▶</b> Play movie</button>${trailerAction()}</div></div></section>${footer()}`;
  app.insertAdjacentHTML("beforeend", mediaInfo(movie, "movie")); bindCommon(); document.querySelector("[data-play-movie]").onclick = () => { state.player = { type:"movie", id:movie.id, title:titleOf(movie), overview:movie.overview, posterPath:movie.poster_path, genreIds:(movie.genres || []).map(genre => genre.id), startAt:0 }; state.route = "player"; render(); }; document.querySelector("[data-trailer]")?.addEventListener("click", showTrailer);
}
function renderSeries() {
  const s = state.series, seasons = (s.seasons || []).filter(x => x.season_number > 0);
  app.innerHTML = `${header()}<button class="back" data-home>‹ Browse</button><section class="detail"><img src="${posterOf(s)}" alt="${escapeHTML(titleOf(s))}"><div><span class="brand">SERIES</span><h1>${escapeHTML(titleOf(s))}</h1><div class="meta"><span>${yearOf(s)}</span><i></i><span>${s.number_of_seasons || seasons.length} seasons</span><i></i><span>${s.vote_average ? `★ ${s.vote_average.toFixed(1)}` : "TV-14"}</span></div><p>${escapeHTML(s.overview || "")}</p><div class="actions"><button class="primary" data-play-series><b>▶</b> Play episode 1</button>${trailerAction()}</div></div></section><section class="episode-section"><div class="rail-title"><h2>Episodes</h2><span>Season ${state.selectedSeason}</span></div><label class="season-select">Season <select id="season-selector" aria-label="Choose season">${seasons.map(x => `<option value="${x.season_number}" ${x.season_number === state.selectedSeason ? "selected" : ""}>Season ${x.season_number}</option>`).join("")}</select></label><div id="episodes-list">${(state.episodes?.episodes || []).map(episode => `<button class="episode" data-play-episode="${episode.episode_number}"><img src="${episode.still_path ? TMDB_IMAGE + episode.still_path : "/icon.svg"}" alt=""><span><b><em>${String(episode.episode_number).padStart(2,"0")}</em>${escapeHTML(episode.name)}</b><small>${escapeHTML(episode.overview || "No description available.")}</small></span><strong>›</strong></button>`).join("")}</div></section>${footer()}`;
  document.querySelector(".detail").insertAdjacentHTML("afterend", mediaInfo(s, "tv")); bindCommon(); document.querySelector("#season-selector").onchange = async event => { state.selectedSeason = Number(event.currentTarget.value); await loadEpisodes(); render(); };
  document.querySelector("[data-play-series]").onclick = () => playEpisode(1, false); document.querySelector("[data-trailer]")?.addEventListener("click", showTrailer);
  document.querySelectorAll("[data-play-episode]").forEach(button => button.onclick = () => playEpisode(Number(button.dataset.playEpisode), false));
}
function showTrailer() { if (!state.trailer?.key) return; app.insertAdjacentHTML("beforeend", `<div class="modal trailer-modal"><section class="trailer-card"><button class="modal-close" data-close>×</button><iframe src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(state.trailer.key)}?autoplay=1&rel=0" title="${escapeHTML(state.trailer.name || "Trailer")}" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe></section></div>`); document.querySelector(".trailer-modal [data-close]").onclick = () => document.querySelector(".trailer-modal")?.remove(); }
function savedStart(item) { try { const saved = JSON.parse(localStorage.getItem(watchKey(item)) || "{}"), time = Math.floor(Number(saved.currentTime) || 0), duration = Number(saved.duration) || 0; return time >= 5 && (!duration || time < duration - 5) ? time : 0; } catch { return 0; } }
function timeLabel(seconds) { const minutes = Math.floor(seconds / 60), remainder = String(seconds % 60).padStart(2, "0"); return `${minutes}:${remainder}`; }
function resumeAction(item, attribute) { const seconds = savedStart(item); return seconds ? `<button class="secondary resume-action" ${attribute}><b>↻</b> Resume from ${timeLabel(seconds)}</button>` : ""; }
function playEpisode(number, resume = false) { const episode = (state.episodes.episodes || []).find(x => x.episode_number === number) || {}, key = { type:"tv", id:state.series.id, season:state.selectedSeason, episode:number }; state.player = { ...key, title:episode.name || titleOf(state.series), overview:episode.overview || state.series.overview, posterPath:episode.still_path || state.series.poster_path, genreIds:(state.series.genres || []).map(genre => genre.id), startAt:resume ? savedStart(key) : 0 }; state.route = "player"; render(); }
function playerURL(item) { const base = item.type === "movie" ? `movie/${item.id}` : `tv/${item.id}/${item.season}/${item.episode}`; return `https://www.vidking.net/embed/${base}?${new URLSearchParams({ color:"b20710", autoPlay:"true", nextEpisode:"true", episodeSelector:"true" })}`; }
function renderPlayer() { const p = state.player, saved = JSON.parse(localStorage.getItem(watchKey(p)) || "{}"); app.innerHTML = `${header()}<button class="back" data-back>‹ Back</button><iframe class="player" src="${playerURL(p)}" allow="autoplay; encrypted-media; fullscreen; picture-in-picture" allowfullscreen></iframe><section class="now"><span class="brand">NOW PLAYING</span><h2>${escapeHTML(p.title)}</h2><div class="progress"><i id="bar" style="width:${saved.progress || 0}%"></i></div><p id="time">${p.startAt ? `Saved at ${timeLabel(p.startAt)} · this player starts safely from the beginning` : savedStart(p) ? `Previously watched until ${timeLabel(savedStart(p))} · playing from the beginning` : escapeHTML(p.overview || "Playback progress is saved on this iPhone.")}</p></section>${footer()}`; bindCommon(); document.querySelector("[data-back]").onclick = () => { state.route = p.type === "tv" ? "series" : "home"; render(); }; }
async function search(query) { state.search = query; if (query.trim().length < 2) { state.searchResults = []; state.route = "home"; render(); return; } try { state.searchResults = results(await api("search/multi", { query })); state.route = "search"; } catch (error) { state.error = error.message; state.route = "home"; } render(); }
function renderSearch() { app.innerHTML = `${header()}<section class="search-page"><span class="brand">DISCOVER</span><h2>Search results</h2>${state.searchResults.length ? `<div class="result-grid">${state.searchResults.map(card).join("")}</div>` : "<p>No matches found. Try a movie, series, or actor name.</p>"}</section>${footer()}`; bindCommon(); }
const GENRES = { 12:"Adventure", 16:"Animation", 18:"Drama", 28:"Action", 35:"Comedy", 53:"Thriller", 80:"Crime", 99:"Documentary", 10749:"Romance", 878:"Science fiction", 9648:"Mystery", 10751:"Family", 10759:"Action & adventure", 10765:"Sci-fi & fantasy" };
function watchedGenres(type = "") { const prefix = type ? `cineva-progress-${type}-` : "cineva-progress-", counts = {}; Object.keys(localStorage).filter(key => key.startsWith(prefix)).forEach(key => { try { (JSON.parse(localStorage.getItem(key) || "{}").genreIds || []).forEach(id => { counts[id] = (counts[id] || 0) + 1; }); } catch {} }); return Object.entries(counts).sort((a, b) => b[1] - a[1]).map(([id]) => Number(id)); }
async function openForYou() { state.route = "for-you"; state.forYou = { loading:true }; render(); const movieGenre = watchedGenres("movie")[0] || watchedGenres()[0], seriesGenre = watchedGenres("tv")[0] || watchedGenres()[0], movieParams = movieGenre ? { with_genres:movieGenre, sort_by:"popularity.desc" } : {}, seriesParams = seriesGenre ? { with_genres:seriesGenre, sort_by:"popularity.desc" } : {}; try { const [movies, series, freshMovies, freshSeries] = await Promise.all([api("discover/movie", movieParams), api("discover/tv", seriesParams), api("movie/now_playing"), api("tv/on_the_air")]); state.forYou = { genre:movieGenre || seriesGenre, rails:{ [movieGenre ? `Because you watch ${GENRES[movieGenre] || "these genres"}` : "Popular picks for you"]:results(movies), [seriesGenre ? `${GENRES[seriesGenre] || "Personalized"} series for you` : "Popular series for you"]:results(series), "New movies":results(freshMovies), "New series":results(freshSeries) } }; } catch (error) { state.forYou = { error:error.message, rails:{} }; } render(); }
function renderForYou() { const view = state.forYou || { loading:true }; app.innerHTML = `${header()}<section class="browse-page"><span class="brand">MADE FOR YOU</span><h2>For You</h2><p>${view.genre ? "Recommendations shaped by the genres in titles you have played." : "Play a title and SEVEN will tune this page to its genres."}</p></section>${view.loading ? `<section class="rail"><div class="skeleton-line wide"></div><div class="cards">${Array.from({length:7}, () => `<div class="card-skeleton skeleton"></div>`).join("")}</div></section>` : view.error ? `<p class="setup">${escapeHTML(view.error)}</p>` : Object.entries(view.rails).map(([name, items]) => rail(name, items)).join("")}${footer()}`; bindCommon(); }
const MOVIE_FILTERS = [["All",null],["Action",28],["Adventure",12],["Animation",16],["Comedy",35],["Crime",80],["Drama",18],["Family",10751],["Horror",27],["Romance",10749],["Sci-Fi",878],["Thriller",53]];
const SERIES_FILTERS = [["All",null],["Action",10759],["Animation",16],["Comedy",35],["Crime",80],["Documentary",99],["Drama",18],["Mystery",9648],["Sci-Fi",10765]];
function discoverGenre(type, genre, sortBy) { const params = { with_genres:genre, sort_by:sortBy }; if (sortBy === "vote_average.desc") params["vote_count.gte"] = 100; return api(`discover/${type}`, params); }
const DEFAULT_CATALOG_FILTERS = { date:"any", score:"", sort:"popularity.desc", certificate:"" };
function filterTrigger() { return `<button class="filter-trigger" data-open-filters aria-label="Open filters"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M7 12h10m-7 6h4"/></svg> Filters</button>`; }
function discoveryParams(type, page, genre, filters) { const params = { sort_by:filters.sort || "popularity.desc", page }; if (genre) params.with_genres = genre; if (filters.score) { params["vote_average.gte"] = filters.score; params["vote_count.gte"] = 50; } const year = new Date().getFullYear(), dateKey = type === "movie" ? "primary_release_date" : "first_air_date"; if (filters.date === "year") params[`${dateKey}.gte`] = `${year}-01-01`; if (filters.date === "five") params[`${dateKey}.gte`] = `${year - 5}-01-01`; if (filters.date === "2010s") { params[`${dateKey}.gte`] = "2010-01-01"; params[`${dateKey}.lte`] = "2019-12-31"; } if (filters.date === "older") params[`${dateKey}.lte`] = "2009-12-31"; if (type === "movie" && filters.certificate) { params.certification_country = "US"; params.certification = filters.certificate; } return params; }
function showCatalogFilters(type) { const saved = { ...DEFAULT_CATALOG_FILTERS, ...(state.catalogFilters?.[type] || {}) }, isMovie = type === "movie"; document.querySelector(".modal")?.remove(); app.insertAdjacentHTML("beforeend", `<div class="modal"><form class="filter-panel" id="catalog-filter-form"><button type="button" class="modal-close" data-close>×</button><span class="brand">FILTER ${isMovie ? "MOVIES" : "SERIES"}</span><h2>Refine your picks</h2><label>Release date<select name="date"><option value="any">Any time</option><option value="year">This year</option><option value="five">Last 5 years</option><option value="2010s">2010–2019</option><option value="older">Before 2010</option></select></label><label>Minimum audience score<select name="score"><option value="">Any score</option><option value="5">5.0+</option><option value="6">6.0+</option><option value="7">7.0+</option><option value="8">8.0+</option></select></label>${isMovie ? `<label>Age rating (US)<select name="certificate"><option value="">Any rating</option><option value="G">G</option><option value="PG">PG</option><option value="PG-13">PG-13</option><option value="R">R</option></select></label>` : `<p class="filter-note">TV age ratings vary by region; SEVEN keeps date and audience-score filters available here.</p>`}<label>Sort by<select name="sort"><option value="popularity.desc">Most popular</option><option value="primary_release_date.desc">Newest release</option><option value="first_air_date.desc">Newest release</option><option value="vote_average.desc">Highest rated</option></select></label><button class="primary auth-submit" type="submit">Show results</button><button class="filter-clear" type="button" data-clear-filters>Clear filters</button></form></div>`); const form = document.querySelector("#catalog-filter-form"); Object.entries(saved).forEach(([name, value]) => { const field = form.elements.namedItem(name); if (field) field.value = value; }); document.querySelector("[data-close]").onclick = () => document.querySelector(".modal")?.remove(); document.querySelector("[data-clear-filters]").onclick = () => { state.catalogFilters ||= {}; state.catalogFilters[type] = { ...DEFAULT_CATALOG_FILTERS }; document.querySelector(".modal")?.remove(); openAllCatalog(type); }; form.onsubmit = event => { event.preventDefault(); const values = new FormData(form); const filters = { date:values.get("date"), score:values.get("score"), sort:values.get("sort"), certificate:values.get("certificate") || "" }; if (type === "tv" && filters.sort === "primary_release_date.desc") filters.sort = "first_air_date.desc"; state.catalogFilters ||= {}; state.catalogFilters[type] = filters; document.querySelector(".modal")?.remove(); openAllCatalog(type, null, 1, false, filters); }; }
async function openCatalog(type, genre = null) { state.route = "catalog"; state.browse = { type, genre, loading:true }; render(); const baseRoutes = type === "movie" ? [["Now playing","movie/now_playing"],["Popular movies","movie/popular"],["Top rated movies","movie/top_rated"],["Coming soon","movie/upcoming"]] : [["On the air","tv/on_the_air"],["Popular series","tv/popular"],["Top rated series","tv/top_rated"],["Airing today","tv/airing_today"]]; const routes = genre ? [[`Popular ${GENRES[genre] || ""}`.trim(),"popularity.desc"],[`Top rated ${GENRES[genre] || ""}`.trim(),"vote_average.desc"],[`New ${GENRES[genre] || ""}`.trim(), type === "movie" ? "primary_release_date.desc" : "first_air_date.desc"]] : baseRoutes; try { const responses = await Promise.all(routes.map(([, route]) => genre ? discoverGenre(type, genre, route) : api(route))); state.browse = { type, genre, rails:Object.fromEntries(routes.map(([name], index) => [name, results(responses[index])])) }; } catch (error) { state.browse = { type, genre, error:error.message, rails:{} }; } render(); }
function renderCatalog() { const view = state.browse || { loading:true, type:"movie" }, label = view.type === "movie" ? "Movies" : "Series", filters = view.type === "movie" ? MOVIE_FILTERS : SERIES_FILTERS; app.innerHTML = `${header()}<section class="browse-page"><span class="brand">EXPLORE SEVEN</span><h2>${label}</h2><p>${view.type === "movie" ? "New releases, crowd favorites, and top-rated films." : "Series that are airing now, popular, and highly rated."}</p><div class="catalog-actions">${filterTrigger()}<button class="all-catalog" data-all-catalog>Browse all ${label.toLowerCase()} <b>›</b></button></div><div class="filter-row" aria-label="Filter ${label}">${filters.map(([name, id]) => `<button class="filter ${view.genre === id ? "active" : ""}" data-filter="${id ?? "all"}">${name}</button>`).join("")}</div></section>${view.loading ? `<section class="rail"><div class="skeleton-line wide"></div><div class="cards">${Array.from({length:7}, () => `<div class="card-skeleton skeleton"></div>`).join("")}</div></section>` : view.error ? `<p class="setup">${escapeHTML(view.error)}</p>` : Object.entries(view.rails).map(([name, items]) => rail(name, items)).join("")}${footer()}`; bindCommon(); document.querySelector("[data-open-filters]").onclick = () => showCatalogFilters(view.type); document.querySelector("[data-all-catalog]").onclick = () => openAllCatalog(view.type); document.querySelectorAll("[data-filter]").forEach(button => button.onclick = () => openCatalog(view.type, button.dataset.filter === "all" ? null : Number(button.dataset.filter))); }
async function openAllCatalog(type, genre = null, page = 1, append = false, selectedFilters = null) { const filters = { ...DEFAULT_CATALOG_FILTERS, ...(selectedFilters || state.catalogFilters?.[type] || {}) }, existing = append ? (state.allCatalog?.items || []) : []; state.route = "all-catalog"; state.allCatalog = { type, genre, page, filters, items:existing, loading:true }; render(); try { const response = await api(`discover/${type}`, discoveryParams(type, page, genre, filters)); state.allCatalog = { type, genre, page, filters, totalPages:Math.min(response.total_pages || 1, 500), items:[...existing, ...results(response)] }; } catch (error) { state.allCatalog = { type, genre, page, filters, items:existing, error:error.message }; } render(); }
function renderAllCatalog() {
  const view = state.allCatalog || { loading:true, type:"movie", items:[] }, label = view.type === "movie" ? "All movies" : "All series", filters = view.type === "movie" ? MOVIE_FILTERS : SERIES_FILTERS;
  const loading = view.loading ? `<div class="catalog-loading skeleton"></div>` : view.page < (view.totalPages || 1) ? `<button class="load-more" data-load-more>Load more ${view.type === "movie" ? "movies" : "series"}</button>` : "";
  const body = view.error ? `<p class="setup">${escapeHTML(view.error)}</p>` : `<div class="result-grid explore-grid">${view.items.map(card).join("")}</div>${loading}`;
  app.innerHTML = `${header()}<button class="back" data-back-all>‹ ${view.type === "movie" ? "Movies" : "Series"}</button><section class="browse-page"><span class="brand">COMPLETE CATALOG</span><h2>${label}</h2><p>Browse the full TMDB catalog, filtered the way you want.</p><div class="catalog-actions">${filterTrigger()}</div><div class="filter-row" aria-label="Filter ${label}">${filters.map(([name, id]) => `<button class="filter ${view.genre === id ? "active" : ""}" data-all-filter="${id ?? "all"}">${name}</button>`).join("")}</div></section>${body}${footer()}`;
  bindCommon(); document.querySelector("[data-back-all]").onclick = () => { state.route = "catalog"; render(); }; document.querySelector("[data-open-filters]").onclick = () => showCatalogFilters(view.type); document.querySelectorAll("[data-all-filter]").forEach(button => button.onclick = () => openAllCatalog(view.type, button.dataset.allFilter === "all" ? null : Number(button.dataset.allFilter))); document.querySelector("[data-load-more]")?.addEventListener("click", () => openAllCatalog(view.type, view.genre, view.page + 1, true));
}
function renderExplore() { const view = state.exploreView; if (!view) { state.route = "home"; return renderHome(); } app.innerHTML = `${header()}<button class="back" data-back-explore>‹ Back</button><section class="search-page"><span class="brand">SEVEN COLLECTION</span><h2>${escapeHTML(view.name)}</h2><p>Browse all ${view.items.length} titles in this collection.</p><div class="result-grid explore-grid">${view.items.map(card).join("")}</div></section>${footer()}`; bindCommon(); document.querySelector("[data-back-explore]").onclick = () => { state.route = view.fromRoute; state.exploreView = null; render(); }; }
function showAuth(mode = "login", message = "") { document.querySelector(".modal")?.remove(); const create = mode === "signup"; app.insertAdjacentHTML("beforeend", `<div class="modal"><form class="auth-card" id="auth-form"><button type="button" class="modal-close" data-close>×</button><span class="brand">SEVEN ACCOUNT</span><h2>${create ? "Create your account" : "Welcome back"}</h2><p>${create ? "Save your progress, watched titles, and settings across devices." : "Sign in to restore your SEVEN history."}</p>${create ? `<label>Display name<input name="displayName" maxlength="50" placeholder="Optional"></label>` : ""}<label>Email<input name="email" type="email" required autocomplete="email" placeholder="you@example.com"></label><label>Password<input name="password" type="password" required minlength="8" autocomplete="${create ? "new-password" : "current-password"}" placeholder="At least 8 characters"></label><p class="form-error" id="auth-message">${escapeHTML(message)}</p><button class="primary auth-submit" type="submit">${create ? "Create account" : "Sign in"}</button><button class="auth-switch" type="button" data-switch>${create ? "Already have an account? Sign in" : "New to SEVEN? Create an account"}</button></form></div>`); document.querySelector("[data-close]").onclick = () => document.querySelector(".modal")?.remove(); document.querySelector("[data-switch]").onclick = () => showAuth(create ? "login" : "signup"); document.querySelector("#auth-form").onsubmit = event => submitAuth(event, mode); }
async function submitAuth(event, mode) { event.preventDefault(); const form = new FormData(event.currentTarget), message = document.querySelector("#auth-message"), submit = event.currentTarget.querySelector("[type=submit]"); submit.disabled = true; message.textContent = ""; try { const payload = { email:form.get("email"), password:form.get("password"), displayName:form.get("displayName") }; let data = await localAPI(`/api/auth/${mode === "signup" ? "signup" : "login"}`, { method:"POST", headers:{ "Content-Type":"application/json" }, body:JSON.stringify(payload) }); if (!data.session && mode === "signup") data = await localAPI("/api/auth/login", { method:"POST", headers:{ "Content-Type":"application/json" }, body:JSON.stringify(payload) }); if (!data.session) { message.textContent = "No sign-in session was returned. Try signing in again."; return; } state.session = data.session; localStorage.setItem(SESSION_KEY, JSON.stringify(data.session)); state.user = data.user || await localAPI("/api/auth/user", { headers:authorizedHeaders() }); await loadCloudProgress(); document.querySelector(".modal")?.remove(); render(); } catch (error) { message.textContent = error.message; } finally { submit.disabled = false; } }
function showAccount() { document.querySelector(".modal")?.remove(); app.insertAdjacentHTML("beforeend", `<div class="modal"><section class="auth-card account-card"><button class="modal-close" data-close>×</button><span class="brand">YOUR ACCOUNT</span><h2>${escapeHTML(state.user?.email || "SEVEN member")}</h2><p>Your watch progress and completed titles sync privately to this account.</p><button class="secondary sign-out" data-signout>Sign out</button></section></div>`); document.querySelector("[data-close]").onclick = () => document.querySelector(".modal")?.remove(); document.querySelector("[data-signout]").onclick = () => { localStorage.removeItem(SESSION_KEY); state.user = null; state.session = null; document.querySelector(".modal")?.remove(); render(); }; }
function queueProgressSync(item, currentTime, duration, progress) { if (!state.session) return; state.pendingProgress = { content_key:watchKey(item), content_type:item.type, tmdb_id:item.id, season:item.season || null, episode:item.episode || null, title:item.title || "Untitled", poster_path:item.posterPath || null, progress_seconds:currentTime, duration_seconds:duration, is_watched:progress >= 90, last_watched_at:new Date().toISOString() }; clearTimeout(state.progressTimer); state.progressTimer = setTimeout(async () => { try { await localAPI("/api/account/progress", { method:"POST", headers:{ "Content-Type":"application/json", ...authorizedHeaders() }, body:JSON.stringify(state.pendingProgress) }); } catch { /* Local progress remains available if cloud sync is offline. */ } }, 1200); }
function bindCommon() { document.querySelectorAll("[data-home]").forEach(button => button.onclick = () => { state.route = "home"; render(); }); document.querySelectorAll("[data-open]").forEach(button => button.onclick = () => { const [type, id] = button.dataset.open.split(":"); openItem(type, id); }); document.querySelectorAll("[data-continue]").forEach(button => button.onclick = () => { const [type, id, season, episode] = button.dataset.continue.split(":"), item = { type, id:Number(id), season:Number(season) || undefined, episode:Number(episode) || undefined }, saved = JSON.parse(localStorage.getItem(watchKey(item)) || "{}"); state.player = { ...item, title:saved.title, overview:"", posterPath:saved.posterPath, genreIds:saved.genreIds || [], startAt:savedStart(item) }; state.route = "player"; render(); }); document.querySelectorAll("[data-explore]").forEach(button => button.onclick = () => { const view = state.explorable?.[button.dataset.explore]; if (!view) return; state.exploreView = view; state.route = "explore"; render(); }); const input = document.querySelector("#search"); let timer; input.oninput = () => { clearTimeout(timer); timer = setTimeout(() => search(input.value), 350); }; document.querySelectorAll("[data-search-focus]").forEach(button => button.onclick = () => input.focus()); document.querySelectorAll("[data-for-you]").forEach(button => button.onclick = openForYou); document.querySelectorAll("[data-movies]").forEach(button => button.onclick = () => openCatalog("movie")); document.querySelectorAll("[data-shows]").forEach(button => button.onclick = () => openCatalog("tv")); document.querySelectorAll("[data-auth]").forEach(button => button.onclick = () => showAuth()); document.querySelectorAll("[data-account]").forEach(button => button.onclick = showAccount); }
window.addEventListener("message", event => { let payload; try { payload = typeof event.data === "string" ? JSON.parse(event.data) : event.data; } catch { return; } if (state.route !== "player" || payload?.type !== "PLAYER_EVENT") return; const data = payload.data || {}, duration = Number(data.duration) || 0, currentTime = Number(data.currentTime) || 0; if (!duration) return; const progress = Math.min(100, currentTime / duration * 100); localStorage.setItem(watchKey(state.player), JSON.stringify({currentTime,duration,progress,watched:progress >= 90,genreIds:state.player.genreIds || [],type:state.player.type,id:state.player.id,season:state.player.season || null,episode:state.player.episode || null,title:state.player.title,posterPath:state.player.posterPath || null,lastWatchedAt:new Date().toISOString()})); queueProgressSync(state.player, currentTime, duration, progress); const bar = document.querySelector("#bar"), time = document.querySelector("#time"); if (bar) bar.style.width = `${progress}%`; if (time) time.textContent = `${Math.floor(currentTime)}s of ${Math.floor(duration)}s`; });
if ("serviceWorker" in navigator) navigator.serviceWorker.register("/service-worker.js");
boot();
