const TMDB_IMAGE = "https://image.tmdb.org/t/p/w500";
const FEATURED_ID = 71712;
const app = document.querySelector("#app");
const state = { featured: null, featuredPool: [], featuredIndex: 0, heroTimer: null, catalog: {}, route: "home", search: "", user: null, session: null, movie: null, trailer: null, progressTimer: null, pendingProgress: null };
const SESSION_KEY = "cineva.supabase.session";
const watchKey = item => `cineva-progress-${item.type}-${item.id}-${item.season || 0}-${item.episode || 0}`;
const titleOf = item => item.title || item.name || item.original_title || item.original_name || "Untitled";
const yearOf = item => (item.release_date || item.first_air_date || "").slice(0, 4);
const posterOf = item => item.poster_path ? `${TMDB_IMAGE}${item.poster_path}` : "/icon.svg";
const escapeHTML = value => String(value || "").replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);

async function localAPI(path, options = {}) { const response = await fetch(path, options); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || data.msg || "Request failed."); return data; }
function authorizedHeaders() { return state.session?.access_token ? { Authorization:`Bearer ${state.session.access_token}` } : {}; }
async function restoreSession() { try { state.session = JSON.parse(localStorage.getItem(SESSION_KEY) || "null"); if (!state.session?.access_token) return; state.user = await localAPI("/api/auth/user", { headers:authorizedHeaders() }); await loadCloudProgress(); } catch { localStorage.removeItem(SESSION_KEY); state.session = null; state.user = null; } }
async function loadCloudProgress() { const rows = await localAPI("/api/account/progress", { headers:authorizedHeaders() }); rows.forEach(row => localStorage.setItem(row.content_key, JSON.stringify({ currentTime:Number(row.progress_seconds), duration:Number(row.duration_seconds), progress:row.duration_seconds ? Number(row.progress_seconds) / Number(row.duration_seconds) * 100 : 0, watched:row.is_watched }))); }

async function api(path, params = {}) {
  const query = new URLSearchParams(params); const response = await fetch(`/api/tmdb/${path}${query.size ? `?${query}` : ""}`);
  if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || "TMDB is not configured");
  return response.json();
}
async function boot() {
  renderLoading();
  await restoreSession();
  try {
    const [featured, trending, movies, shows, recent, airing] = await Promise.all([
      api(`tv/${FEATURED_ID}`), api("trending/all/week"), api("movie/popular"), api("tv/popular"), api("movie/now_playing"), api("tv/on_the_air")
    ]);
    state.featuredPool = shuffle([...results(recent), ...results(airing), ...results(trending)]).filter(item => item.backdrop_path).slice(0, 12);
    state.featured = state.featuredPool[0] || normalize(featured, "tv");
    state.catalog = { "Trending now": results(trending), "New movies": results(recent), "New series": results(airing), "Popular movies": results(movies), "Popular series": results(shows) };
  } catch (error) {
    state.featured = { id: FEATURED_ID, type: "tv", name: "The Good Doctor", overview: "Add a TMDB Read Access Token to enable posters, descriptions, categories, and search.", backdrop_path: null };
    state.catalog = {};
    state.error = error.message;
  }
  render();
}
function shuffle(items) { const copy = [...items]; for (let index = copy.length - 1; index > 0; index -= 1) { const target = Math.floor(Math.random() * (index + 1)); [copy[index], copy[target]] = [copy[target], copy[index]]; } return copy; }
function results(payload) { return (payload.results || []).filter(item => item.media_type !== "person").map(item => normalize(item)); }
function normalize(item, fallbackType) { return { ...item, type: item.type || (item.media_type === "movie" || item.title ? "movie" : fallbackType || "tv") }; }
function header() { const account = state.user ? `<button class="account signed-in" data-account title="Account">${escapeHTML((state.user.email || "U").slice(0, 1).toUpperCase())}</button>` : `<button class="account" data-auth aria-label="Open account"><span>◉</span><b>Account</b></button>`; return `<header><button class="wordmark" data-home aria-label="Jovia home">JOVIA</button><nav><button class="nav-link" data-home>Home</button><button class="nav-link" data-search-focus>Search</button></nav><label class="search"><span>⌕</span><input id="search" value="${escapeHTML(state.search)}" placeholder="Titles, movies, series" autocomplete="off"></label>${account}</header>`; }
function render() { if (state.route === "player") return renderPlayer(); if (state.route === "movie") return renderMovie(); if (state.route === "series") return renderSeries(); if (state.route === "search") return renderSearch(); renderHome(); }
function renderLoading() { app.innerHTML = `<header><span class="wordmark">JOVIA</span></header><section class="hero skeleton"></section><section class="rail"><div class="skeleton-line wide"></div><div class="cards">${Array.from({length:7}, () => `<div class="card-skeleton skeleton"></div>`).join("")}</div></section><section class="rail"><div class="skeleton-line"></div><div class="cards">${Array.from({length:7}, () => `<div class="card-skeleton skeleton"></div>`).join("")}</div></section>`; }
function renderHome() {
  clearInterval(state.heroTimer);
  const f = state.featured;
  app.innerHTML = `${header()}<section class="hero" id="featured">${featuredMarkup(f)}</section>${state.error ? `<p class="setup">TMDB setup needed: ${escapeHTML(state.error)}. See README.</p>` : ""}<div id="rails">${Object.entries(state.catalog).map(([name, items]) => rail(name, items)).join("")}</div>`;
  bindCommon(); bindFeatured(); scheduleHero();
}
function heroDots() { const count = Math.min(5, state.featuredPool.length), active = Math.round(state.featuredIndex / Math.max(1, state.featuredPool.length - 1) * Math.max(0, count - 1)); return Array.from({ length:count }, (_, index) => `<i class="${index === active ? "active" : ""}"></i>`).join(""); }
function featuredMarkup(item) { const dots = state.featuredPool.length > 1 ? `<div class="hero-nav"><button class="hero-arrow" data-hero-prev aria-label="Previous featured title">‹</button><span class="hero-dots">${heroDots()}</span><button class="hero-arrow" data-hero-next aria-label="Next featured title">›</button></div>` : ""; return `<div class="hero-image" style="${item.backdrop_path ? `background-image:linear-gradient(90deg,#050505 5%,#050505bb 48%,#0505053d 100%),url(${TMDB_IMAGE}${item.backdrop_path})` : ""}"></div><div class="hero-copy"><span class="brand">NEW ON JOVIA</span><h1>${escapeHTML(titleOf(item))}</h1><div class="meta"><span>${yearOf(item) || "New"}</span><i></i><span>${item.vote_average ? `★ ${item.vote_average.toFixed(1)}` : "TV-14"}</span><i></i><span>${item.type === "tv" ? "Series" : "Movie"}</span></div><p>${escapeHTML(item.overview || "A new title ready to discover on Jovia.")}</p><div class="actions"><button class="primary" data-open="${item.type}:${item.id}"><b>▶</b> View title</button><button class="secondary" data-open="${item.type}:${item.id}"><b>ⓘ</b> More info</button></div></div>${dots}`; }
function bindFeatured() { document.querySelectorAll("#featured [data-open]").forEach(button => button.onclick = () => { const [type, id] = button.dataset.open.split(":"); openItem(type, id); }); document.querySelector("[data-hero-prev]")?.addEventListener("click", () => rotateHero(-1)); document.querySelector("[data-hero-next]")?.addEventListener("click", () => rotateHero(1)); }
function rotateHero(direction = 1) { if (state.featuredPool.length < 2) return; state.featuredIndex = (state.featuredIndex + direction + state.featuredPool.length) % state.featuredPool.length; state.featured = state.featuredPool[state.featuredIndex]; const hero = document.querySelector("#featured"); if (!hero) return; hero.classList.remove("hero-swap"); void hero.offsetWidth; hero.innerHTML = featuredMarkup(state.featured); hero.classList.add("hero-swap"); bindFeatured(); }
function scheduleHero() { if (state.featuredPool.length > 1) state.heroTimer = setInterval(() => { if (state.route === "home") rotateHero(); }, 8500); }
function rail(name, items) { return `<section class="rail"><div class="rail-title"><h2>${name}</h2><span>Explore all</span></div><div class="cards">${items.map(card).join("")}</div></section>`; }
function card(item) { return `<button class="card" data-open="${item.type}:${item.id}"><span class="poster-wrap"><img src="${posterOf(item)}" alt="" loading="lazy"><i>${item.type === "tv" ? "SERIES" : "MOVIE"}</i><strong class="card-play" aria-hidden="true">▶</strong></span><b>${escapeHTML(titleOf(item))}</b><small>${yearOf(item) || "New"}${item.vote_average ? ` · ★ ${item.vote_average.toFixed(1)}` : ""}</small></button>`; }
async function openItem(type, id) {
  try {
    const item = normalize(await api(`${type}/${id}`), type);
    state.trailer = await loadTrailer(type, item.id);
    if (type === "movie") { state.movie = item; state.route = "movie"; }
    else { state.series = item; state.selectedSeason = 1; state.route = "series"; await loadEpisodes(); }
  } catch (error) { state.error = error.message; state.route = "home"; }
  render();
}
async function loadEpisodes() { state.episodes = await api(`tv/${state.series.id}/season/${state.selectedSeason}`); }
async function loadTrailer(type, id) { try { const videos = await api(`${type}/${id}/videos`); return (videos.results || []).find(video => video.site === "YouTube" && video.type === "Trailer") || (videos.results || []).find(video => video.site === "YouTube") || null; } catch { return null; } }
function trailerAction() { return state.trailer ? `<button class="secondary" data-trailer><b>▷</b> Trailer</button>` : ""; }
function renderMovie() {
  const movie = state.movie;
  app.innerHTML = `${header()}<button class="back" data-home>‹ Browse</button><section class="detail"><img src="${posterOf(movie)}" alt="${escapeHTML(titleOf(movie))}"><div><span class="brand">MOVIE</span><h1>${escapeHTML(titleOf(movie))}</h1><div class="meta"><span>${yearOf(movie)}</span><i></i><span>${movie.runtime ? `${movie.runtime} min` : "Movie"}</span><i></i><span>${movie.vote_average ? `★ ${movie.vote_average.toFixed(1)}` : "TV-14"}</span></div><p>${escapeHTML(movie.overview || "")}</p><div class="actions"><button class="primary" data-play-movie><b>▶</b> Play movie</button>${trailerAction()}</div></div></section>`;
  bindCommon(); document.querySelector("[data-play-movie]").onclick = () => { state.player = { type:"movie", id:movie.id, title:titleOf(movie), overview:movie.overview, posterPath:movie.poster_path }; state.route = "player"; render(); }; document.querySelector("[data-trailer]")?.addEventListener("click", showTrailer);
}
function renderSeries() {
  const s = state.series, seasons = (s.seasons || []).filter(x => x.season_number > 0);
  app.innerHTML = `${header()}<button class="back" data-home>‹ Browse</button><section class="detail"><img src="${posterOf(s)}" alt="${escapeHTML(titleOf(s))}"><div><span class="brand">SERIES</span><h1>${escapeHTML(titleOf(s))}</h1><div class="meta"><span>${yearOf(s)}</span><i></i><span>${s.number_of_seasons || seasons.length} seasons</span><i></i><span>${s.vote_average ? `★ ${s.vote_average.toFixed(1)}` : "TV-14"}</span></div><p>${escapeHTML(s.overview || "")}</p><div class="actions"><button class="primary" data-play-series><b>▶</b> Play episode 1</button>${trailerAction()}</div></div></section><section class="episode-section"><div class="rail-title"><h2>Episodes</h2><span>Season ${state.selectedSeason}</span></div><div class="season-row">${seasons.map(x => `<button class="season ${x.season_number === state.selectedSeason ? "active" : ""}" data-season="${x.season_number}">Season ${x.season_number}</button>`).join("")}</div><div id="episodes-list">${(state.episodes?.episodes || []).map(episode => `<button class="episode" data-play-episode="${episode.episode_number}"><img src="${episode.still_path ? TMDB_IMAGE + episode.still_path : "/icon.svg"}" alt=""><span><b><em>${String(episode.episode_number).padStart(2,"0")}</em>${escapeHTML(episode.name)}</b><small>${escapeHTML(episode.overview || "No description available.")}</small></span><strong>›</strong></button>`).join("")}</div></section>`;
  bindCommon(); document.querySelectorAll("[data-season]").forEach(button => button.onclick = async () => { state.selectedSeason = Number(button.dataset.season); await loadEpisodes(); render(); });
  document.querySelector("[data-play-series]").onclick = () => playEpisode(1); document.querySelector("[data-trailer]")?.addEventListener("click", showTrailer);
  document.querySelectorAll("[data-play-episode]").forEach(button => button.onclick = () => playEpisode(Number(button.dataset.playEpisode)));
}
function showTrailer() { if (!state.trailer?.key) return; app.insertAdjacentHTML("beforeend", `<div class="modal trailer-modal"><section class="trailer-card"><button class="modal-close" data-close>×</button><iframe src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(state.trailer.key)}?autoplay=1&rel=0" title="${escapeHTML(state.trailer.name || "Trailer")}" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe></section></div>`); document.querySelector(".trailer-modal [data-close]").onclick = () => document.querySelector(".trailer-modal")?.remove(); }
function playEpisode(number) { const episode = (state.episodes.episodes || []).find(x => x.episode_number === number) || {}; state.player = { type:"tv", id:state.series.id, season:state.selectedSeason, episode:number, title:episode.name || titleOf(state.series), overview:episode.overview || state.series.overview, posterPath:episode.still_path || state.series.poster_path }; state.route = "player"; render(); }
function playerURL(item) { const base = item.type === "movie" ? `movie/${item.id}` : `tv/${item.id}/${item.season}/${item.episode}`; return `https://www.vidking.net/embed/${base}?${new URLSearchParams({color:"b20710",autoPlay:"true",nextEpisode:"true",episodeSelector:"true"})}`; }
function renderPlayer() { const p = state.player, saved = JSON.parse(localStorage.getItem(watchKey(p)) || "{}"); app.innerHTML = `${header()}<button class="back" data-back>‹ Back</button><iframe class="player" src="${playerURL(p)}" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe><section class="now"><span class="brand">NOW PLAYING</span><h2>${escapeHTML(p.title)}</h2><div class="progress"><i id="bar" style="width:${saved.progress || 0}%"></i></div><p id="time">${saved.currentTime ? `Resume from ${Math.floor(saved.currentTime)} seconds` : escapeHTML(p.overview || "Playback progress is saved on this iPhone.")}</p></section>`; bindCommon(); document.querySelector("[data-back]").onclick = () => { state.route = p.type === "tv" ? "series" : "home"; render(); }; }
async function search(query) { state.search = query; if (query.trim().length < 2) { state.searchResults = []; state.route = "home"; render(); return; } try { state.searchResults = results(await api("search/multi", { query })); state.route = "search"; } catch (error) { state.error = error.message; state.route = "home"; } render(); }
function renderSearch() { app.innerHTML = `${header()}<section class="search-page"><span class="brand">DISCOVER</span><h2>Search results</h2>${state.searchResults.length ? `<div class="result-grid">${state.searchResults.map(card).join("")}</div>` : "<p>No matches found. Try a movie, series, or actor name.</p>"}</section>`; bindCommon(); }
function showAuth(mode = "login", message = "") { document.querySelector(".modal")?.remove(); const create = mode === "signup"; app.insertAdjacentHTML("beforeend", `<div class="modal"><form class="auth-card" id="auth-form"><button type="button" class="modal-close" data-close>×</button><span class="brand">CINEVA ACCOUNT</span><h2>${create ? "Create your account" : "Welcome back"}</h2><p>${create ? "Save your progress, watched titles, and settings across devices." : "Sign in to restore your Cineva history."}</p>${create ? `<label>Display name<input name="displayName" maxlength="50" placeholder="Optional"></label>` : ""}<label>Email<input name="email" type="email" required autocomplete="email" placeholder="you@example.com"></label><label>Password<input name="password" type="password" required minlength="8" autocomplete="${create ? "new-password" : "current-password"}" placeholder="At least 8 characters"></label><p class="form-error" id="auth-message">${escapeHTML(message)}</p><button class="primary auth-submit" type="submit">${create ? "Create account" : "Sign in"}</button><button class="auth-switch" type="button" data-switch>${create ? "Already have an account? Sign in" : "New to Cineva? Create an account"}</button></form></div>`); document.querySelector("[data-close]").onclick = () => document.querySelector(".modal")?.remove(); document.querySelector("[data-switch]").onclick = () => showAuth(create ? "login" : "signup"); document.querySelector("#auth-form").onsubmit = event => submitAuth(event, mode); }
async function submitAuth(event, mode) { event.preventDefault(); const form = new FormData(event.currentTarget), message = document.querySelector("#auth-message"), submit = event.currentTarget.querySelector("[type=submit]"); submit.disabled = true; message.textContent = ""; try { const payload = { email:form.get("email"), password:form.get("password"), displayName:form.get("displayName") }; let data = await localAPI(`/api/auth/${mode === "signup" ? "signup" : "login"}`, { method:"POST", headers:{ "Content-Type":"application/json" }, body:JSON.stringify(payload) }); if (!data.session && mode === "signup") data = await localAPI("/api/auth/login", { method:"POST", headers:{ "Content-Type":"application/json" }, body:JSON.stringify(payload) }); if (!data.session) { message.textContent = "No sign-in session was returned. Try signing in again."; return; } state.session = data.session; localStorage.setItem(SESSION_KEY, JSON.stringify(data.session)); state.user = data.user || await localAPI("/api/auth/user", { headers:authorizedHeaders() }); await loadCloudProgress(); document.querySelector(".modal")?.remove(); render(); } catch (error) { message.textContent = error.message; } finally { submit.disabled = false; } }
function showAccount() { document.querySelector(".modal")?.remove(); app.insertAdjacentHTML("beforeend", `<div class="modal"><section class="auth-card account-card"><button class="modal-close" data-close>×</button><span class="brand">YOUR ACCOUNT</span><h2>${escapeHTML(state.user?.email || "Cineva member")}</h2><p>Your watch progress and completed titles sync privately to this account.</p><button class="secondary sign-out" data-signout>Sign out</button></section></div>`); document.querySelector("[data-close]").onclick = () => document.querySelector(".modal")?.remove(); document.querySelector("[data-signout]").onclick = () => { localStorage.removeItem(SESSION_KEY); state.user = null; state.session = null; document.querySelector(".modal")?.remove(); render(); }; }
function queueProgressSync(item, currentTime, duration, progress) { if (!state.session) return; state.pendingProgress = { content_key:watchKey(item), content_type:item.type, tmdb_id:item.id, season:item.season || null, episode:item.episode || null, title:item.title || "Untitled", poster_path:item.posterPath || null, progress_seconds:currentTime, duration_seconds:duration, is_watched:progress >= 90, last_watched_at:new Date().toISOString() }; clearTimeout(state.progressTimer); state.progressTimer = setTimeout(async () => { try { await localAPI("/api/account/progress", { method:"POST", headers:{ "Content-Type":"application/json", ...authorizedHeaders() }, body:JSON.stringify(state.pendingProgress) }); } catch { /* Local progress remains available if cloud sync is offline. */ } }, 1200); }
function bindCommon() { document.querySelectorAll("[data-home]").forEach(button => button.onclick = () => { state.route = "home"; render(); }); document.querySelectorAll("[data-open]").forEach(button => button.onclick = () => { const [type, id] = button.dataset.open.split(":"); openItem(type, id); }); const input = document.querySelector("#search"); let timer; input.oninput = () => { clearTimeout(timer); timer = setTimeout(() => search(input.value), 350); }; document.querySelectorAll("[data-search-focus]").forEach(button => button.onclick = () => input.focus()); document.querySelectorAll("[data-auth]").forEach(button => button.onclick = () => showAuth()); document.querySelectorAll("[data-account]").forEach(button => button.onclick = showAccount); }
window.addEventListener("message", event => { let payload; try { payload = typeof event.data === "string" ? JSON.parse(event.data) : event.data; } catch { return; } if (state.route !== "player" || payload?.type !== "PLAYER_EVENT") return; const data = payload.data || {}, duration = Number(data.duration) || 0, currentTime = Number(data.currentTime) || 0; if (!duration) return; const progress = Math.min(100, currentTime / duration * 100); localStorage.setItem(watchKey(state.player), JSON.stringify({currentTime,duration,progress,watched:progress >= 90})); queueProgressSync(state.player, currentTime, duration, progress); const bar = document.querySelector("#bar"), time = document.querySelector("#time"); if (bar) bar.style.width = `${progress}%`; if (time) time.textContent = `${Math.floor(currentTime)}s of ${Math.floor(duration)}s`; });
if ("serviceWorker" in navigator) navigator.serviceWorker.register("/service-worker.js");
boot();
